# Generated by Django 4.2.3 on 2023-07-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='_author_rating',
        ),
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.IntegerField(default=0),
        ),
    ]
