# Generated by Django 4.2.3 on 2023-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0002_remove_author__author_rating_author_author_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('A', 'Статья'), ('N', 'Новость')], max_length=2),
        ),
    ]
