# Generated by Django 4.2.3 on 2023-08-07 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0003_alter_post_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsportalapp.author')),
                ('category_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsportalapp.category')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='author_subscribers',
            field=models.ManyToManyField(through='newsportalapp.AuthorCategory', to='newsportalapp.category'),
        ),
    ]
