# Generated by Django 4.2.3 on 2023-08-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0006_subscribecategory_subscribers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='subscribers',
            new_name='subscribe_category',
        ),
        migrations.RenameField(
            model_name='subscribers',
            old_name='subscribers_user',
            new_name='subscribe_user',
        ),
    ]
