# Generated by Django 4.2.3 on 2023-08-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0007_rename_subscribers_subscribers_subscribe_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribecategory',
            old_name='author_connection',
            new_name='subscriber_connection',
        ),
    ]
