# Generated by Django 4.2.3 on 2023-08-13 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('newsportalapp', '0008_rename_author_connection_subscribecategory_subscriber_connection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='subscribe_category',
        ),
        migrations.RemoveField(
            model_name='subscribers',
            name='subscribe_user',
        ),
        migrations.RemoveField(
            model_name='author',
            name='author_subscribers',
        ),
        migrations.AddField(
            model_name='category',
            name='category_subscribe',
            field=models.ManyToManyField(through='newsportalapp.SubscribeCategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscribecategory',
            name='subscriber_connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AuthorCategory',
        ),
        migrations.DeleteModel(
            name='Subscribers',
        ),
    ]
