# Generated by Django 4.2.3 on 2023-09-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0009_remove_subscribers_subscribe_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='Это категория клиента', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.ManyToManyField(through='newsportalapp.PostCategory', to='newsportalapp.category', verbose_name='This is the help text'),
        ),
    ]
