# Generated by Django 4.2.3 on 2023-09-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0010_alter_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(help_text='category name', max_length=50, unique=True),
        ),
    ]
