# Generated by Django 4.2.3 on 2023-09-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsportalapp', '0011_alter_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_name_en_us',
            field=models.CharField(help_text='category name', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name_ru',
            field=models.CharField(help_text='category name', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_en_us',
            field=models.CharField(max_length=124, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_title_ru',
            field=models.CharField(max_length=124, null=True),
        ),
    ]
